### ISSUE TITLE
Attribute *Disabled* is added to getAddressbutton

### ISSUE THREAD

**Issue by nlii** [sveawebpay/magento-module#11]
In Invoice template the getAddress button looks like this in code:
https://github.com/sveawebpay/magento-module/blob/master/src/app/design/frontend/base/default/template/svea/payment/service/invoice.phtml#L107

When inspecting it in browser it looks like this:
```php
<button id="getAddress" class="button" type="button" disabled="" autocomplete="off">
```
This blocks the prototype we use to execute the button. When i remove the disabled attribute in firebug, it works.

In Mage 1.5 it works with changing the `<button>` to `<a>` but it looks wrong in1.7

This button also disapears in some one step checkouts

**Comment by jonathanselander** [comment]
Fixed upstream
