### ISSUE TITLE
Checkout not working for denmark (since 4.1.6)

### ISSUE THREAD

**Issue by matsolastrom** [sveawebpay/magento-module#141]
Checkout is broken with svea card payment Denmark only (4.1.6, worked before update). Normal magento checkout redirects to cart page when pressing "Place order" in checkout. Tried stock magento checkout and lightcheckout from gomage.

This appears in apache logs:

PHP Fatal error:  Call to undefined method Svea\\CreateOrderBuilder::setPayPageLanguage() in ***/app/code/community/Svea/WebPay/Model/Hosted/Card.php on line 54

**Comment by jonathanselander** [comment]
Thanks for the report, wi well work on a patch for it

**Comment by jonathanselander** [comment]
@matsolastrom please have a look at https://github.com/sveawebpay/magento-module/pull/143

**Comment by matsolastrom** [comment]
#143 confirmed working fix for #141

//MO


- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -



Mats-Ola Ström



E-mail:       matsola@tailorstore.com
Mobile:       +46 (0) 708 25 41 26
Fax:             +46 (0) 42 42 42 088
Web:           www.tailorstore.com


Tailor Store Sweden AB
Garnisonsgatan 48 | 254 66 Helsingborg, Sweden

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
