### ISSUE TITLE
Invoicefee should be on confirmation e-mail

### ISSUE THREAD

**Issue by nlii** [sveawebpay/magento-module#20]
It's included in the total price, but not specified in Subtotal in the mail.

In checkout it's there:
![magentocheckout](https://f.cloud.github.com/assets/3532400/1179382/44eef138-21d3-11e3-8ead-175d3eed8d45.PNG)

But not in e-mail confirmation to customer:
![magentomailconfirm](https://f.cloud.github.com/assets/3532400/1179385/50217508-21d3-11e3-8091-fc1edc940897.PNG)

**Comment by jonathanselander** [comment]
Fixed upstream
