### ISSUE TITLE
Invoicefee tax not included on total

### ISSUE THREAD

**Issue by nlii** [sveawebpay/magento-module#23]
The invoicefee is shown in order-total-block as incl.tax, when creating an invoice. But tax is not included in the totalprice. The right amount is sent to Svea when creating Invoice (amount excl. tax + tax %), and the right amount is sent back as authorized from Svea, but it is registered in Magento excl. tax.

eg.
![invoicemagento](https://f.cloud.github.com/assets/3532400/1237884/a64fca9c-29df-11e3-937d-4955b1dcb2e6.PNG)

**Comment by jonathanselander** [comment]
Fixed upstream
