### ISSUE TITLE
Configured 'Paid order status' for invoice doesn't work

### ISSUE THREAD

**Issue by andreas-binea** [sveawebpay/magento-module#24]
In the admin configuration we've set the Paid order status to "Faktura skapad hos SveaWebPay". When ordering something with invoice, the status of the order is however not set correctly. The statuses are changed in this order

1. Faktura skapad hos SveaWebPay (status 'sveawebpay_accepted' in state 'new')
2. Processing (status 'processing' in state 'processing')
3. Pending (status 'pending' in state 'new').

What is going on here? When going from 2 to 3, it should change back to 'Faktura skapad hos SveaWebPay', not Pending?

What seems to be the bug is that 'Pending' is the default status for state 'new'. So when going from 2 to 3, the module does not respect what is configured in admin, but just chooses the default status.

![configuration system magento admin - google chrome_2013-10-01_17-02-57](https://f.cloud.github.com/assets/5196997/1255011/fa5e645a-2b7d-11e3-9981-0e5687e5e688.png)

![10005 orders sales magento admin - google chrome_2013-10-01_17-03-30](https://f.cloud.github.com/assets/5196997/1255004/d3fa7010-2b7d-11e3-8e08-6597babe4cc7.png)

![order statuses sales magento admin - google chrome_2013-10-01_17-04-36](https://f.cloud.github.com/assets/5196997/1255070/d5b9b5ae-2b7e-11e3-8016-0c2c55919ea1.png)

**Comment by jonathanselander** [comment]
Fixed upstream, uses processing state order statuses
