### ISSUE TITLE
Invoice fee not specified to order mail

### ISSUE THREAD

**Issue by PhpMadman** [sveawebpay/magento-module#5]
On magento 1.7.2, the invoice fee is not specified in order confirmation mail.
But it's added to the total fee.
See bellow: 

Productname  qty:2 	2 000,00 kr
Summa 	  2 500,00 kr
Leverans 	    0,00 kr
Moms 	    500,00 kr
Totalt 	     2 539,00 kr

**Comment by jonathanselander** [comment]
Fixed upstream
