### ISSUE TITLE
Code Field is not showing directly.

### ISSUE THREAD

**Issue by Vanqaqi** [sveawebpay/magento-module#66]
Hello, 
I have been trying to figure that out, but kinda hard. So, when i go over the checkout the field for the code is not showing and i have to proceed with the checkout and then go back to see it. Although, this is "OK" for me to guess, for someone non-technical that would be a problem.
Any ideas?
![1](https://cloud.githubusercontent.com/assets/5840317/2932584/d7b54536-d7b2-11e3-8eaa-9f8903dded32.png)

**Comment by jonathanselander** [comment]
Fixed upstream
