### ISSUE TITLE
Shipping information missing in the invoice

### ISSUE THREAD

**Issue by nlii** [sveawebpay/magento-module#9]
(Copied from email In Swedish)
Vi använder fraktmodulen Premium MaxiRate från WebShopApps. Vi har aldrig haft några problem med fraktbeskrivningen när vi kört Payson, DIBS eller Klarna. Kanske kan vara så att de har specialahanterat den modulen, men jag tvivlar på det.

Varje fraktslag har ju två delar av sin beskrivning. Tror de benämns Titel och Metod. Det är viktigt att ha med båda. Vi har alltid Titel till tomma strängen, och Metod benämner vi så som vi önskar att fraktalternativet ska visas. Annars blir fraktinformationen till slutkund bara konstig (med avseende på vad som visas i frontend, i epost osv). Magento är inte helt optimalt där tyvärr.

![invoices - google chrome_2013-08-09_12-41-00](https://f.cloud.github.com/assets/3532400/947118/8a76a92e-0349-11e3-8188-ae650a68be1f.png)

**Comment by jonathanselander** [comment]
Fixed upstream
